pipeline 
{
    agent any
    environment {
        TF_VAR_aws_region="${aws_region}"
        TF_VAR_aws_access_key = credentials('aws_access_key')
        TF_VAR_aws_secret_key = credentials('aws_secret_key')
        TF_VAR_s3_bucket="${s3_bucket}"
        TF_VAR_dynamodb_table="${dynamodb_table}"
        TF_VAR_project="${project}"
        TF_VAR_aws_key_pair="${aws_key_pair}"
    }

     parameters {
        string(name: 'aws_region', defaultValue: 'us-east-1', description: 'AWS region where all the resources will be created',)
        string(name: 'project', defaultValue: 'test', description: 'Name of terraform project',)
        string(name: 's3_bucket', defaultValue: 'terraform-eks-s3-bucket', description: 'Name of S3 bucket',)
        string(name: 'dynamodb_table', defaultValue: 'eks-dynamodb-lock-table', description: 'Name of DynamoDB table',)
        string(name: 'aws_key_pair', defaultValue: 'eks-terraform-key', description: 'AWS Key pair',)
        choice(name: 'action', description: '', choices: ['plan','apply' , 'destroy'])
    }
    stages {
        stage("Terraform Setup/init"){
            steps {
                sh '''
                pwd
                ls -ltr
                terraform init -reconfigure -backend-config="access_key=$TF_VAR_aws_access_key" -backend-config="secret_key=$TF_VAR_aws_secret_key"
                '''
            }
        }
        stage("Terraform dry-run"){
            steps{                  
                sh '''
                echo "Project Name --> "$TF_VAR_project
                terraform plan -var="aws_access_key=$TF_VAR_aws_access_key" -var="aws_secret_key=$TF_VAR_aws_secret_key"
                 '''
            }
        }
        stage("Terraform Action"){
            steps{
                sh '''
                if [ $action = "plan" ]; then
                    terraform plan -var="aws_access_key=$TF_VAR_aws_access_key" -var="aws_secret_key=$TF_VAR_aws_secret_key"
                else
                    terraform ${action} --auto-approve -var="aws_access_key=$TF_VAR_aws_access_key" -var="aws_secret_key=$TF_VAR_aws_secret_key"
                fi
                '''
            }
        }

    }
}
